### ISSUE TITLE
Support for pillbug, ladybug and mosquito

### ISSUE THREAD

**Issue by pardahlman** [vidstige/thehive#1]
Hello 👋,

I love _The Hive_ and in between the games this summer I thought about writing an AI for it, too 😉. We should meet up for lunch and game when we're back from vacation!

Noticed that your code doesn't contain definitions of the extensions tiles [lady bug](https://boardgamegeek.com/boardgame/70704/hive-ladybug), [mosquito](https://boardgamegeek.com/boardgame/30323/hive-mosquito) and the game changer [pillbug](https://boardgamegeek.com/boardgame/139666/hive-pillbug). You should check them out if you haven't already!

**Comment by vidstige** [comment]
Hi!
Thanks for noticing. :-) It doesn't even work for beetle yet, so that's a first! And the AI is pretty stupid. Just pushed some code to enter manual moves now at least. Let's meet up for sure!
